model_name: "qwen2.5-vl-3b"
num_layers: 36
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
norm_path: "model.norm"
voc_path: "lm_head"
